version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: 'EST5EDT'
      DNS: '8.8.8.8'
    networks:
      - default
    #read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /opt/seedbox/vpn:/vpn
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    depends_on:
      - vpn
    environment:
      - TZ=EST5EDT
      - WEBUI_PORT=8080
      - PUID=107
      - GUID=995
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /opt/seedbox/qbittorrent:/config
      - /opt/seedbox/downloads:/downloads
#    ports:
#      - 6881:6881
#      - 6881:6881/udp
#      - 8080:8080

networks:
  default:
