#!/bin/bash

RCLONE_REMOTE='your-remote:your-bucket'

for user in $(v-list-sys-users plain)
do
    echo "Backing up $user..."
    BKOUT=`v-backup-user $user | grep "Local:" | awk '{print $4}'`
    echo "Uploading $BKOUT to remote..."
    rclone move $BKOUT $RCLONE_REMOTE
done
